android: [Reland] [PowerPC] frontend get target feature from backend with cpu name
Porting of commit bf79d48 "[Reland] [PowerPC] frontend get target feature from backend with cpu name"

Fixes the following building error:

external/llvm-project/llvm/lib/TargetParser/PPCTargetParser.cpp:20:10: fatal error: 'llvm/TargetParser/PPCGenTargetFeatures.inc' file not found
   20 | #include "llvm/TargetParser/PPCGenTargetFeatures.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.